# -*- coding: utf-8 -*-
"""Car Features and MSRP .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lxVuQc98rrx0zSesPu_SM8p3E00RltwB
"""

import numpy as np
import pandas as pd

dataset = pd.read_csv("data.csv")
dataset.head()

dataset.isnull().sum()

dataset = dataset.dropna(subset=["Engine Fuel Type"])
dataset["Engine HP"] = dataset["Engine HP"].fillna(dataset["Engine HP"].mean())
dataset["Engine Cylinders"] = dataset["Engine Cylinders"].fillna(dataset["Engine Cylinders"].mean())
dataset["Number of Doors"] = dataset["Number of Doors"].fillna(dataset["Number of Doors"].mode()[0])
dataset["Market Category"] = dataset["Market Category"].fillna("Unknown")

dataset.isnull().sum()

dataset = dataset.drop(columns = "Model")
dataset = dataset.drop(columns = "Market Category")
top_makes = dataset["Make"].value_counts().nlargest(15).index
dataset["Make"] = dataset["Make"].apply(lambda x: x if x in top_makes else "Other")
dataset = pd.get_dummies(dataset,columns = ["Make"],prefix="Make")

dataset.head()
dataset["Vehicle Size"].unique()

dataset = pd.get_dummies(dataset,columns = ["Engine Fuel Type","Transmission Type","Driven_Wheels","Vehicle Style"])
size_mapping = {"Compact" : 0,"Midsize" : 1,"Large" : 2}
dataset["Vehicle Size"] = dataset["Vehicle Size"].map(size_mapping)
dataset.head()

dataset.dtypes

dataset["MSRP"].describe()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize = (10,5))
sns.histplot(dataset["MSRP"],bins = 50, kde = True)
plt.title("MSRP dağılımı")

plt.figure(figsize = (10,5))
sns.histplot(np.log1p(dataset["MSRP"]), bins = 50,kde = True, color = "orange")
plt.title("log Sonrası MSRP Dönüşümü")

dataset["MSRP"] = np.log1p(dataset["MSRP"])